"""baseline: all 6 tables

Revision ID: bb1fcc46b21f
Revises: 
Create Date: 2026-07-29 16:48:34.494060

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'bb1fcc46b21f'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def _now_default():
    """时间戳默认值：SQLite 用 (CURRENT_TIMESTAMP)，PostgreSQL 用 now()
    （PG 不接受带括号的 CURRENT_TIMESTAMP 语法）。"""
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        return sa.text("now()")
    return sa.text("(CURRENT_TIMESTAMP)")


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('global_config',
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('users',
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('security_question', sa.Text(), server_default='', nullable=True),
    sa.Column('security_answer_hash', sa.String(length=256), server_default='', nullable=True),
    sa.Column('status', sa.String(length=32), server_default='active', nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=_now_default(), nullable=True),
    sa.PrimaryKeyConstraint('username')
    )
    op.create_index(op.f('ix_users_status'), 'users', ['status'], unique=False)
    op.create_table('codes',
    sa.Column('code_id', sa.String(length=32), nullable=False),
    sa.Column('tier', sa.String(length=32), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), server_default='unused', nullable=True),
    sa.Column('bound_username', sa.String(length=128), server_default='', nullable=True),
    sa.Column('activated_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=_now_default(), nullable=True),
    sa.Column('created_by', sa.String(length=64), server_default='', nullable=True),
    sa.ForeignKeyConstraint(['bound_username'], ['users.username'], ),
    sa.PrimaryKeyConstraint('code_id')
    )
    op.create_index(op.f('ix_codes_status'), 'codes', ['status'], unique=False)
    op.create_index(op.f('ix_codes_tier'), 'codes', ['tier'], unique=False)
    op.create_table('device_grants',
    sa.Column('pc_hash', sa.String(length=128), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('token', sa.Text(), nullable=False),
    sa.Column('enrolled', sa.Integer(), server_default='0', nullable=True),
    sa.Column('fingerprint', sa.String(length=256), server_default='', nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=_now_default(), nullable=True),
    sa.ForeignKeyConstraint(['username'], ['users.username'], ),
    sa.PrimaryKeyConstraint('pc_hash')
    )
    op.create_index(op.f('ix_device_grants_username'), 'device_grants', ['username'], unique=False)
    op.create_table('device_registry',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('fingerprint', sa.String(length=256), server_default='', nullable=True),
    sa.Column('hostname', sa.String(length=256), server_default='', nullable=True),
    sa.Column('os', sa.String(length=128), server_default='', nullable=True),
    sa.Column('os_arch', sa.String(length=32), server_default='', nullable=True),
    sa.Column('last_active_at', sa.DateTime(), server_default=_now_default(), nullable=True),
    sa.Column('bound_at', sa.DateTime(), server_default=_now_default(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=_now_default(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=_now_default(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.username'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'fingerprint', name='uq_user_fingerprint')
    )
    op.create_index(op.f('ix_device_registry_user_id'), 'device_registry', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_device_registry_user_id'), table_name='device_registry')
    op.drop_table('device_registry')
    op.drop_index(op.f('ix_device_grants_username'), table_name='device_grants')
    op.drop_table('device_grants')
    op.drop_index(op.f('ix_codes_tier'), table_name='codes')
    op.drop_index(op.f('ix_codes_status'), table_name='codes')
    op.drop_table('codes')
    op.drop_index(op.f('ix_users_status'), table_name='users')
    op.drop_table('users')
    op.drop_table('global_config')
    # ### end Alembic commands ###
