"""仓储接口层：服务层只依赖这些 Protocol，不感知底层数据库（SQLite / CloudBase PG HTTP API）。

方法签名只出现领域对象；SQL 与 pg_http 两个实现都遵循本接口。
"""
from __future__ import annotations

from datetime import date
from typing import Protocol

from app.domain.devices import DeviceGrant, DeviceRegistry
from app.domain.identity import User
from app.domain.licensing import ActivationCode


class UserRepo(Protocol):
    def get(self, username: str) -> User | None: ...
    def exists(self, username: str) -> bool: ...
    def create(self, user: User) -> User: ...
    def update_password(self, username: str, new_password_hash: str) -> None: ...
    def update_security(self, username: str, question: str, answer_hash: str) -> None: ...
    def update_theme(self, username: str, theme: str) -> None: ...
    def flush(self) -> None:
        """SQLite 下确保用户行已持久化（后续试用码 FK 依赖）；HTTP 后端无 FK 顺序问题，no-op。"""
        ...

    # ── 账号自助注销（account-deletion）：全部单语句 CAS，返回受影响行数 ──
    def request_deletion(self, username: str, requested_at, deadline, waive: bool) -> int:
        """受理注销申请。WHERE deletion_status='正常'；0 行=已在流程中（幂等）。"""
        ...
    def revoke_deletion(self, username: str, now) -> int:
        """撤销注销。WHERE status='注销撤销期' AND deadline>now；0 行=已到期或无申请。"""
        ...
    def mark_deleted(self, username: str, now) -> int:
        """到期执行标记（含 password_hash 置空）。WHERE status='注销撤销期' AND deadline<=now。"""
        ...
    def find_due_deletion_usernames(self, now) -> list[str]:
        """补偿扫描：deletion_status='注销撤销期' AND deadline<=now 的用户名。"""
        ...


class CodeRepo(Protocol):
    def get(self, code_id: str) -> ActivationCode | None: ...
    def find_all_by_username(self, username: str) -> list[ActivationCode]: ...
    def find_active_by_username(self, username: str) -> list[ActivationCode]: ...
    def find_all(self, limit: int = 200) -> list[ActivationCode]: ...
    def create(self, code: ActivationCode) -> None: ...
    def activate(self, code_id: str, username: str, expires_at: date) -> None: ...
    def find_unconsumed_by_username(self, username: str) -> list[ActivationCode]:
        """unused（待激活）+ active（排队中/消耗中）——注销阻塞与清单口径（R2）。"""
        ...
    def revoke_unconsumed_for_user(self, username: str) -> int:
        """注销执行：该用户 unused/active（待激活+排队中+消耗中）全部置 revoked。返回行数。"""
        ...
    def request_refund_for_user(self, code_id: str, username: str, now) -> int:
        """权益级退款申请（account-deletion）：CAS 标记 refund_requested_at。
        WHERE 绑定本人 + 未消耗 + 未申请；0 行=状态已被并发方改变（幂等）。"""
        ...

    # ── 支付台账（s-pay-foundation：到货-激活两段式）──
    def create_from_order(self, code_id: str, tier: str, duration_days: int,
                          user_id: int, order_id: int, now) -> bool:
        """发货插台账行（status=pending_activation，grant_start 空）。
        撞 code_id 唯一键返回 False（发货幂等键）。"""
        ...
    def find_by_order(self, order_id: int) -> list[ActivationCode]:
        """按订单查台账行（激活入口）。"""
        ...
    def revoke_unconsumed_for_order(self, order_no: str) -> int:
        """退款收回：该订单未激活台账行（发货键 O-{order_no}，unused/pending_activation）
        置 revoked；已激活行不动——部分退款按秒折算，用户保留剩余权益。返回行数。"""
        ...
    def revoke_queued_for_order(self, order_no: str, anchor) -> int:
        """退款收回（排队相位）：该订单 active 且 grant_start 为空或 > anchor 的台账行
        置 revoked。anchor=该单 refund_requested_at（naive UTC），与折算金额锁定同锚——
        若按退款成功时刻判，冷静期窗口内跨起算点会复现「全额退+码保留」同构 bug。
        已起算行（grant_start <= anchor）不动。返回行数。"""
        ...
    def find_active_by_user_id(self, user_id: int) -> list[ActivationCode]:
        """已激活行（顺延起点计算）。"""
        ...
    def activate_pending(self, code_id: str, grant_start, expires_at, activated_at) -> bool:
        """CAS pending_activation→active（写入 grant_start/expires_at）。
        False=状态已被并发方改走（重复激活/已退）。"""
        ...

    def redeem_unused(self, code_id: str, user_id: int, grant_start, expires_at, activated_at) -> bool:
        """CAS unused→active（s-code-redeem：管理端手工码兑换）。绑定 user_id，
        写入 activated_at/grant_start/expires_at。False=状态已被并发方改走
        （重复兑换/他人已兑），归属与到期不被改写。"""
        ...

    def find_codes_page(self, user_id: int, statuses: list[str] | None = None,
                        limit: int = 20, offset: int = 0) -> tuple[list[ActivationCode], int]:
        """我的套餐明细分页（license-grants-pagination）：(当前页行, total)。
        名下全部台账行（订单来源＋激活码兑换；unused 未兑换行不是套餐恒排除）；
        statuses=None=全部；created_at 倒序（裁定：分页排序下推 DB，不做状态分组）。"""
        ...


class DeviceRepo(Protocol):
    def get_by_fingerprint(self, user_id: str, fingerprint: str) -> DeviceRegistry | None: ...
    def list_by_user(self, user_id: str) -> list[DeviceRegistry]: ...
    def upsert(self, device: DeviceRegistry) -> DeviceRegistry: ...
    def delete_by_id(self, device_id: str, user_id: str) -> bool: ...
    def delete_all_for_user(self, user_id: str) -> int:
        """注销执行：清空该用户全部设备绑定。返回行数。"""
        ...


class GrantRepo(Protocol):
    def get(self, pc_hash: str) -> DeviceGrant | None: ...
    def upsert(
        self, pc_hash: str, username: str, token: str, enrolled: bool, fingerprint: str,
        *, challenge: str | None = None,
    ) -> None: ...
    def set_enrolled(self, pc_hash: str, username: str, enrolled: bool) -> None: ...
    def delete_by_fingerprint(self, username: str, fingerprint: str) -> int:
        """移除设备时同步清除该设备授权凭证（防被移设备继续持有效令牌）。R5。"""
        ...
    def delete_all_for_user(self, username: str) -> int:
        """注销执行：清空该用户全部设备授权。返回行数。"""
        ...


class ConfigRepo(Protocol):
    def get(self, key: str, default: str = "") -> str: ...
