"""24 个预置题材定义。

机械转写自 client/frontend/src/data/genres.ts（去掉前端专用 icon 字段），
camelCase 键名与前端 GenreDefinition 一致，供 genres/service.ensure_seed_genres()
在启动时幂等播种。用户对预置题材的编辑（如改名）不会被 seed 覆盖。
"""

PRESET_GENRES: list[dict] = [
    # ── 都市系 ──────────────────────────────────────────────────────────
    {
        "id": "urban-daily",
        "name": "都市日常",
        "description": "以现代城市为背景，聚焦普通人的日常生活、情感纠葛与成长故事。",
        "category": "urban",
        "narratorRole": "靠近主角内心的全知第三人称，语气温和略带共情",
        "typicalArc": "主角面对生活困境 → 逐步努力改变 → 收获成长或感悟",
        "taboos": ["超自然元素", "过度戏剧化", "脱离现实的巧合"],
        "promptInjection": "[都市日常基调] 保持真实感，细节从日常场景出发，对话自然不做作",
        "toneBlueprint": {
            "defaultTone": "温暖写实",
            "atmosphereOptions": ["温馨治愈", "现实沉重", "轻快明亮", "青春怀旧"],
            "povOptions": ["第三人称有限视角", "第一人称自述"],
            "techniqueTags": ["场景细节描写", "对话推进叙事", "心理活动穿插"],
        },
        "genreConfig": {
            "fulfillmentTypes": ["人物成长", "情感圆满", "生活感悟"],
            "chapterTypes": ["日常", "冲突", "转折", "感悟"],
            "pacingRules": ["每天推进不超过 3 个场景", "每章至少 1 次情感刻画"],
        },
        "storyArcTemplates": [
            {"id": "growth", "name": "成长弧", "description": "主角从迷茫到找到自我的过程", "beats": ["日常困境", "转折事件", "挣扎", "领悟"]},
            {"id": "romance", "name": "情感弧", "description": "两人从相识到相知的情感历程", "beats": ["相遇", "走近", "冲突", "和解"]},
            {"id": "milestone", "name": "人生切片", "description": "人生重要节点的片段式叙事", "beats": ["铺陈", "高潮事件", "余韵"]},
        ],
    },
    {
        "id": "urban-supernatural",
        "name": "都市异能",
        "description": "现代都市背景下，主角拥有超自然能力，在平凡中隐藏不凡。",
        "category": "urban",
        "narratorRole": "跟随主角视角的第三人称，悬念驱动，少量全知视角做铺垫",
        "typicalArc": "主角觉醒能力 → 卷入异能世界冲突 → 建立新秩序",
        "taboos": ["能力无限膨胀", "削弱现实感", "过度解释能力原理"],
        "promptInjection": "[都市异能基调] 保持都市真实感，能力使用有代价有限制，战斗描写节奏紧凑",
        "toneBlueprint": {
            "defaultTone": "悬念紧张",
            "atmosphereOptions": ["暗流涌动", "都市夜景", "日常中隐藏异常", "热血战斗"],
            "povOptions": ["第三人称有限视角", "多视角交替"],
            "techniqueTags": ["悬念设置", "动作描写快节奏", "日常与异常交替"],
        },
        "genreConfig": {
            "fulfillmentTypes": ["能力成长", "势力平衡", "隐藏身份保护"],
            "chapterTypes": ["日常伪装", "异能冲突", "势力交锋", "秘密揭露"],
            "pacingRules": ["打斗场景不超过 2 章连续", "每 3 章安排 1 章日常缓冲"],
        },
        "storyArcTemplates": [
            {"id": "awakening", "name": "觉醒弧", "description": "主角从平凡到觉醒，逐渐了解异能世界", "beats": ["平凡日常", "觉醒事件", "探索期", "危机爆发"]},
            {"id": "conspiracy", "name": "阴谋弧", "description": "揭开隐藏在都市下的巨大阴谋", "beats": ["异常信号", "追查", "真相逼近", "正面冲突"]},
        ],
    },
    {
        "id": "urban-cultivation",
        "name": "都市修真",
        "description": "修真元素融入现代都市，古老传承与现代文明的碰撞。",
        "category": "urban",
        "narratorRole": "全知的修真者视角，带适度的神秘感和宏大时空观",
        "typicalArc": "主角获得传承 → 在都市中修炼提升 → 解决超自然危机",
        "taboos": ["修真等级膨胀", "都市味全失变成纯修仙", "配角智商掉线"],
        "promptInjection": "[都市修真基调] 将修真体系与现代都市结合，修炼过程具象化，战斗融入城市环境",
        "toneBlueprint": {
            "defaultTone": "热血神秘",
            "atmosphereOptions": ["古老与现代碰撞", "仙气缭绕", "暗夜修真", "宗门复兴"],
            "povOptions": ["第三人称全知", "主角聚焦视角"],
            "techniqueTags": ["修炼具象化描写", "都市打斗场景融合", "等级递进清晰"],
        },
        "genreConfig": {
            "fulfillmentTypes": ["修为突破", "宗门重建", "守护都市"],
            "chapterTypes": ["修炼", "都市日常", "斗法", "传承揭秘"],
            "pacingRules": ["修炼章节不超过 3 章连续", "每章至少 1 个都市场景元素"],
        },
        "storyArcTemplates": [
            {"id": "reclusive-master", "name": "隐居高手", "description": "隐于都市的高手被迫出手", "beats": ["隐于市", "事件触发", "展现实力", "卷入更深"]},
            {"id": "inheritance", "name": "传承之秘", "description": "获得古老传承后的成长之路", "beats": ["意外获得", "初窥门径", "觊觎者", "守护传承"]},
        ],
    },
    {
        "id": "business-war",
        "name": "商战职场",
        "description": "聚焦商业竞争、职场博弈，以智谋和策略为核心的都市故事。",
        "category": "urban",
        "narratorRole": "冷静分析的第三人称，偏叙事距离远，保持客观商业叙事风格",
        "typicalArc": "主角进入行业 → 摸清规则 → 遭遇危机 → 用智谋翻盘",
        "taboos": ["烂俗感情线喧宾夺主", "对手智商过低", "暴富爽文套路"],
        "promptInjection": "[商战职场基调] 商业逻辑合理，博弈过程有来有回，细节有真实感",
        "toneBlueprint": {
            "defaultTone": "冷静智斗",
            "atmosphereOptions": ["办公室政治", "谈判博弈", "创业热血", "并购风云"],
            "povOptions": ["第三人称有限视角", "双视角对抗"],
            "techniqueTags": ["对话博弈描写", "商业细节真实感", "心理战刻画"],
        },
        "genreConfig": {
            "fulfillmentTypes": ["商业目标达成", "智谋胜利", "行业影响"],
            "chapterTypes": ["布局", "交锋", "转折", "收网"],
            "pacingRules": ["每场商战不超过 5 章", "每章含至少有 1 次对话博弈"],
        },
        "storyArcTemplates": [
            {"id": "turnaround", "name": "逆袭弧", "description": "弱势方通过智谋翻盘", "beats": ["劣势开局", "积蓄力量", "关键一搏", "逆转胜"]},
            {"id": "takeover", "name": "收购弧", "description": "企业并购中的明争暗斗", "beats": ["收购意向", "尽职调查", "暗流", "成交或破裂"]},
        ],
    },

    # ── 历史系 ──────────────────────────────────────────────────────────
    {
        "id": "historical-alt",
        "name": "历史架空",
        "description": "基于历史背景但进行大幅度虚构改编，重塑历史格局。",
        "category": "historical",
        "narratorRole": "大历史视角的第三人称全知，宏观叙事偶尔切入微观人物",
        "typicalArc": "历史变局开启 → 主角投身浪潮 → 改变历史走向",
        "taboos": ["严重违背基础历史逻辑", "现代价值观强加", "历史人物过于脸谱化"],
        "promptInjection": "[历史架空基调] 保持时代感，语言风格适度文白夹杂，权谋逻辑严密",
        "toneBlueprint": {
            "defaultTone": "宏大史诗",
            "atmosphereOptions": ["金戈铁马", "朝堂风云", "市井烟火", "乱世飘零"],
            "povOptions": ["第三人称全知", "多线索并行视角"],
            "techniqueTags": ["历史氛围营造", "权谋逻辑链", "群像描写"],
        },
        "genreConfig": {
            "fulfillmentTypes": ["格局改变", "势力统一", "文明进步"],
            "chapterTypes": ["朝堂", "战场", "市井", "谋略"],
            "pacingRules": ["权谋章节与动作章节交替", "每卷至少 1 次重大历史事件"],
        },
        "storyArcTemplates": [
            {"id": "unification", "name": "统一之途", "description": "乱世中走向统一的过程", "beats": ["乱世起", "势力割据", "合纵连横", "定鼎"]},
            {"id": "reform", "name": "变法图强", "description": "推行改革改变国运", "beats": ["积弊", "立志革新", "阻力", "变法成效"]},
        ],
    },
    {
        "id": "historical-time-travel",
        "name": "历史穿越",
        "description": "现代人穿越到古代，用现代知识改变历史的爽文类型。",
        "category": "historical",
        "narratorRole": "带现代意识的主角视角，有古今碰撞的幽默感和反差",
        "typicalArc": "穿越到古代 → 用现代知识立足 → 改变局部历史 → 面临更大挑战",
        "taboos": ["知识滥用无代价", "历史进程完全魔改", "配角集体降智"],
        "promptInjection": "[历史穿越基调] 古今价值观冲突要有深度，现代知识带来改变但有适应成本",
        "toneBlueprint": {
            "defaultTone": "轻松爽快带思考",
            "atmosphereOptions": ["古今碰撞", "生存奋斗", "技术革命", "朝堂周旋"],
            "povOptions": ["第一人称穿越者", "第三人称有限视角"],
            "techniqueTags": ["古今反差幽默", "知识应用合理化", "时代细节考究"],
        },
        "genreConfig": {
            "fulfillmentTypes": ["改变命运", "技术革新", "势力建立"],
            "chapterTypes": ["穿越适应", "技术推广", "冲突解决", "势力扩张"],
            "pacingRules": ["知识应用要有铺垫", "每 5 章安排 1 章反思"],
        },
        "storyArcTemplates": [
            {"id": "industrial", "name": "工业革命", "description": "在古代掀起技术革命", "beats": ["穿越初醒", "发现优势", "小试牛刀", "改变时代"]},
            {"id": "survival", "name": "古代求生", "description": "穿越后先求生存再图发展", "beats": ["适应环境", "立足", "危机", "站稳脚跟"]},
        ],
    },
    {
        "id": "historical-court",
        "name": "古风权谋",
        "description": "古代宫廷、官场中的权术、智谋与斗争。",
        "category": "historical",
        "narratorRole": "冷静深沉的第三人称全知，看透每步棋背后的算计",
        "typicalArc": "主角置身权力漩涡 → 步步为营 → 扳倒对手 → 实现政治抱负",
        "taboos": ["言情喧宾夺主", "反派智商不在线", "权谋儿戏化"],
        "promptInjection": "[古风权谋基调] 每一步行动都有动机和后果，权谋讲究七分铺垫三分爆发",
        "toneBlueprint": {
            "defaultTone": "深沉智斗",
            "atmosphereOptions": ["深宫暗流", "朝堂角力", "边疆风云", "世家博弈"],
            "povOptions": ["第三人称全知", "多视角罗生门"],
            "techniqueTags": ["伏笔铺垫", "对话弦外之音", "心理博弈"],
        },
        "genreConfig": {
            "fulfillmentTypes": ["权力获得", "恩怨了结", "天下安定"],
            "chapterTypes": ["布局", "角力", "收网", "余波"],
            "pacingRules": ["每步权谋至少 3 章铺垫", "每章至少 1 次有深意的对话"],
        },
        "storyArcTemplates": [
            {"id": "scheme", "name": "连环计", "description": "精心设计的连环计谋", "beats": ["设局", "请君入瓮", "变数", "收网"]},
            {"id": "purge", "name": "清理门户", "description": "清除内部威胁的权谋", "beats": ["内鬼预警", "暗中调查", "引蛇出洞", "一网打尽"]},
        ],
    },
    {
        "id": "military-war",
        "name": "军事战争",
        "description": "以战争为核心的历史/架空军事故事，聚焦战略、战术与军人精神。",
        "category": "historical",
        "narratorRole": "宏观战略与微观战场交错的第三人称，苍凉而热血",
        "typicalArc": "战争爆发 → 主角从基层崛起 → 关键战役扭转局势",
        "taboos": ["战争浪漫化", "敌方弱智化", "个人英雄主义过度"],
        "promptInjection": "[军事战争基调] 战争描写的残酷感不能少，战术细节有依据，军人情感厚重",
        "toneBlueprint": {
            "defaultTone": "热血悲壮",
            "atmosphereOptions": ["金戈铁马", "运筹帷幄", "绝境突围", "和平代价"],
            "povOptions": ["第三人称多视角", "战场与帅帐交替"],
            "techniqueTags": ["战争场面宏大描写", "战术逻辑合理", "士兵群像"],
        },
        "genreConfig": {
            "fulfillmentTypes": ["战役胜利", "格局改变", "军人使命完成"],
            "chapterTypes": ["战前", "交锋", "僵持", "转折"],
            "pacingRules": ["大战间隔至少 3 章铺垫", "每章保持至少 1 条人物线"],
        },
        "storyArcTemplates": [
            {"id": "decisive-battle", "name": "决战弧", "description": "一场决定命运的战役", "beats": ["战前部署", "接战", "胶着", "底牌", "胜负"]},
            {"id": "rise", "name": "崛起弧", "description": "小兵成长为将军之路", "beats": ["入伍", "初战", "磨砺", "成名之战"]},
        ],
    },

    # ── 玄幻系 ──────────────────────────────────────────────────────────
    {
        "id": "fantasy",
        "name": "玄幻奇幻",
        "description": "完全虚构的世界，魔法、斗气、诸神等超自然力量体系。",
        "category": "xianhuan",
        "narratorRole": "史诗感的第三人称全知，偶尔切换到角色内心制造共情",
        "typicalArc": "平凡少年 → 获得机缘 → 踏上修炼之路 → 对抗黑暗势力",
        "taboos": ["等级无限膨胀", "配角沦为经验包", "修炼过程流水账"],
        "promptInjection": "[玄幻奇幻基调] 世界构造要有独特性，力量体系设定清晰，战斗有战术而非纯堆战力",
        "toneBlueprint": {
            "defaultTone": "冒险史诗",
            "atmosphereOptions": ["异世界冒险", "学院成长", "黑暗崛起", "诸神之战"],
            "povOptions": ["第三人称全知", "主角聚焦视角"],
            "techniqueTags": ["世界构建", "力量体系具象化", "战斗场面层次感"],
        },
        "genreConfig": {
            "fulfillmentTypes": ["境界突破", "宝物获取", "守护重要的人"],
            "chapterTypes": ["修炼", "冒险", "战斗", "揭秘"],
            "pacingRules": ["突破间隔至少 5 章", "每卷 1 次阶段性 BOSS 战"],
        },
        "storyArcTemplates": [
            {"id": "journey", "name": "冒险之旅", "description": "从新手村到世界之巅的旅程", "beats": ["出发", "第一个挑战", "伙伴集结", "黑暗逼近", "终局之战"]},
            {"id": "school", "name": "学院风云", "description": "在魔法学院中成长、竞争的故事", "beats": ["入学", "初露锋芒", "学院大赛", "外部危机"]},
        ],
    },
    {
        "id": "xianxia",
        "name": "仙侠修真",
        "description": "以中国传统修仙文化为背景，讲求因果、机缘、道心的修炼故事。",
        "category": "xianhuan",
        "narratorRole": "带有东方哲学韵味的第三人称，既见天地也见众生",
        "typicalArc": "凡人踏入修仙 → 历经磨难 → 明悟道心 → 飞升或守护",
        "taboos": ["纯爽文无深度", "修仙等级爆炸", "道心轻浮"],
        "promptInjection": "[仙侠修真基调] 修真求道的过程要有哲思，因果循环贯彻全书，法术体系有美感",
        "toneBlueprint": {
            "defaultTone": "唯美深邃",
            "atmosphereOptions": ["仙气飘渺", "凡尘历练", "宗门纷争", "天地大劫"],
            "povOptions": ["第三人称全知", "有限视角带入体悟"],
            "techniqueTags": ["意境描写", "道法自然哲思", "斗法诗意化"],
        },
        "genreConfig": {
            "fulfillmentTypes": ["修为突破", "因果了结", "护道卫道"],
            "chapterTypes": ["悟道", "历练", "斗法", "了因果"],
            "pacingRules": ["突破需机缘铺垫", "每阶段安排心魔考验"],
        },
        "storyArcTemplates": [
            {"id": "mortal-to-immortal", "name": "凡人修仙", "description": "从凡人一步步飞升的漫漫长路", "beats": ["入门", "筑基", "游历", "仙魔之争", "飞升"]},
            {"id": "reincarnation", "name": "轮回觉醒", "description": "大能转世重修的觉醒之路", "beats": ["前世缘", "今生觉醒", "宿敌", "超越前世"]},
        ],
    },
    {
        "id": "eastern-fantasy",
        "name": "东方玄幻",
        "description": "融合东方神话与玄幻元素，家族、血脉、传承为核心。",
        "category": "xianhuan",
        "narratorRole": "充满力量的第三人称，节奏明快，爽点密集",
        "typicalArc": "废柴/天才被贬 → 激活血脉/传承 → 逆袭打脸 → 登顶巅峰",
        "taboos": ["打脸套路化", "女角色工具化", "血脉等级无限深"],
        "promptInjection": "[东方玄幻基调] 热血战斗为主，打脸情节要有铺垫，家族宗门有真实生态",
        "toneBlueprint": {
            "defaultTone": "热血激昂",
            "atmosphereOptions": ["家族纷争", "宗门大比", "远古遗迹", "万族争霸"],
            "povOptions": ["第三人称主角视角", "偶尔切换对手视角"],
            "techniqueTags": ["战斗爽感", "血脉觉醒高潮", "势力博弈"],
        },
        "genreConfig": {
            "fulfillmentTypes": ["血脉觉醒", "实力碾压", "家族荣耀"],
            "chapterTypes": ["修炼", "战斗", "夺宝", "势力冲突"],
            "pacingRules": ["每 10 章 1 次高潮", "修炼与战斗交替"],
        },
        "storyArcTemplates": [
            {"id": "revenge", "name": "王者归来", "description": "被贬低的天才重新证明自己", "beats": ["落魄", "机缘", "回归", "打脸", "问鼎"]},
            {"id": "heritage", "name": "远古传承", "description": "探索远古秘境获得传承", "beats": ["秘境现世", "群雄汇聚", "试炼闯关", "传承之争"]},
        ],
    },
    {
        "id": "otherworld",
        "name": "异世大陆",
        "description": "主角穿越或转生到完全陌生的异世界，从零开始生存与崛起。",
        "category": "xianhuan",
        "narratorRole": "跟随主角探索的第三人称有限视角，惊讶和发现感贯穿始终",
        "typicalArc": "穿越到异世界 → 了解世界规则 → 建立势力 → 面对世界级危机",
        "taboos": ["开局无敌", "异世界同质化", "金手指过于万能"],
        "promptInjection": "[异世大陆基调] 世界观要有独到之处，金手指有使用限制和代价，文明差异有深度",
        "toneBlueprint": {
            "defaultTone": "探索冒险",
            "atmosphereOptions": ["异域风情", "文明碰撞", "荒野求生", "争霸天下"],
            "povOptions": ["第一人称穿越体验", "第三人称有限视角"],
            "techniqueTags": ["世界观逐步揭示", "文化差异描写", "生存智慧"],
        },
        "genreConfig": {
            "fulfillmentTypes": ["势力建立", "文明融合", "世界探索"],
            "chapterTypes": ["探索", "生存", "建设", "征战"],
            "pacingRules": ["新设定逐步展开", "力量成长有阶段感"],
        },
        "storyArcTemplates": [
            {"id": "survival", "name": "异界求生", "description": "在陌生世界活下去并强大起来", "beats": ["初临", "适应", "立足", "崛起"]},
            {"id": "civilization", "name": "文明播种", "description": "用现代/异域知识改变异世界", "beats": ["发现差距", "引入新知识", "改变", "冲突与融合"]},
        ],
    },

    # ── 悬疑系 ──────────────────────────────────────────────────────────
    {
        "id": "mystery",
        "name": "悬疑推理",
        "description": "以谜团为核心，通过线索搜集和逻辑推理解开真相。",
        "category": "suspense",
        "narratorRole": "冷静理性的第三人称，信息量与读者同步或稍多，保持公平推理",
        "typicalArc": "案件/谜团出现 → 调查收集线索 → 多重反转 → 真相大白",
        "taboos": ["天降线索", "凶手一出场就知道", "超自然解释一切"],
        "promptInjection": "[悬疑推理基调] 线索公平呈现给读者，推理过程逻辑闭环，每章结尾留有悬念",
        "toneBlueprint": {
            "defaultTone": "冷静悬疑",
            "atmosphereOptions": ["本格推理", "社会派反思", "密室困局", "连环迷案"],
            "povOptions": ["侦探主角视角", "多嫌疑犯视角交替"],
            "techniqueTags": ["线索埋设", "红鲱鱼误导", "逻辑推理链"],
        },
        "genreConfig": {
            "fulfillmentTypes": ["真相揭露", "正义伸张", "谜题解答"],
            "chapterTypes": ["案发", "调查", "推理", "反转", "真相"],
            "pacingRules": ["每案至少 3 次反转", "线索均匀分布在章节中"],
        },
        "storyArcTemplates": [
            {"id": "whodunit", "name": "谁是凶手", "description": "封闭空间的连环命案调查", "beats": ["命案发生", "现场勘查", "嫌疑人", "抽丝剥茧", "真相反转"]},
            {"id": "cold-case", "name": "旧案重查", "description": "多年前的悬案被重新打开", "beats": ["旧案重现", "新线索", "证人", "推翻旧论", "尘封真相"]},
        ],
    },
    {
        "id": "horror",
        "name": "恐怖惊悚",
        "description": "营造恐惧氛围，探索未知恐怖来源的心理或超自然故事。",
        "category": "suspense",
        "narratorRole": "极度贴近主角的有限视角，信息差制造恐惧，让读者与主角一同发现危险",
        "typicalArc": "日常中感知异常 → 逐步深入恐怖源头 → 直面恐惧 → 逃出生天或覆灭",
        "taboos": ["Jump scare 滥用", "解释过度消灭恐怖感", "主角光环不死"],
        "promptInjection": "[恐怖惊悚基调] 恐惧来自未知和心理暗示，氛围营造重于视觉恐怖，留白让读者想象",
        "toneBlueprint": {
            "defaultTone": "压抑恐惧",
            "atmosphereOptions": ["心理恐怖", "克苏鲁式未知", "都市怪谈", "密闭空间"],
            "povOptions": ["第一人称沉浸式", "第三人称贴近视角"],
            "techniqueTags": ["氛围渲染", "心理压迫", "留白与暗示"],
        },
        "genreConfig": {
            "fulfillmentTypes": ["活下来", "揭开恐怖源头", "打破循环"],
            "chapterTypes": ["异常", "探索", "危机", "直面"],
            "pacingRules": ["紧张与松弛交替", "每章至少 1 次恐怖感升级"],
        },
        "storyArcTemplates": [
            {"id": "descent", "name": "逐步沦陷", "description": "从正常世界逐渐滑入恐怖深渊", "beats": ["日常异常", "否认", "深入调查", "无法回头", "终局"]},
            {"id": "survival", "name": "绝境逃生", "description": "在恐怖环境中求生", "beats": ["陷阱/被困", "初步应对", "绝望", "一线生机", "逃出"]},
        ],
    },
    {
        "id": "supernatural-ghost",
        "name": "灵异志怪",
        "description": "中国传统志怪风格的灵异故事，狐仙、鬼怪、因果报应。",
        "category": "suspense",
        "narratorRole": "说书人风格的第三人称，带因果宿命的中国传统叙事韵味",
        "typicalArc": "灵异事件出现 → 探查背后因果 → 化解怨念或收服妖邪",
        "taboos": ["纯恐怖无因果", "鬼怪只是工具", "收服无代价"],
        "promptInjection": "[灵异志怪基调] 因果报应贯穿始终，志怪元素有中国传统文化根基，阴阳两界平衡",
        "toneBlueprint": {
            "defaultTone": "玄妙惊悚",
            "atmosphereOptions": ["阴阳两界", "狐仙传说", "因果循环", "道法自然"],
            "povOptions": ["第三人称说书人", "天师/主角视角"],
            "techniqueTags": ["志怪氛围", "因果线埋设", "民间传说融入"],
        },
        "genreConfig": {
            "fulfillmentTypes": ["怨念化解", "因果了结", "阴阳平衡"],
            "chapterTypes": ["异象", "探查", "因果", "收服/超度"],
            "pacingRules": ["每个灵异事件有完整因果", "每 2-3 章一个灵异单元"],
        },
        "storyArcTemplates": [
            {"id": "karma", "name": "因果弧", "description": "一段跨越前世今生的因果故事", "beats": ["现世孽", "探查", "前世揭示", "忏悔/救赎", "果报"]},
            {"id": "case-file", "name": "志怪档案", "description": "单元式灵异事件集", "beats": ["报案", "现场", "斗法", "了结"]},
        ],
    },
    {
        "id": "crime",
        "name": "犯罪刑侦",
        "description": "以刑事案件侦查为核心，写实风格的警匪/犯罪心理故事。",
        "category": "suspense",
        "narratorRole": "写实风格的第三人称多视角，刑警专业视角与罪犯视角交替",
        "typicalArc": "案件发生 → 警方介入侦查 → 罪犯周旋 → 心理博弈 → 缉拿归案",
        "taboos": ["刑侦手段魔幻化", "反派独白过多", "程序正义被无视"],
        "promptInjection": "[犯罪刑侦基调] 侦查过程有现实依据，罪犯画像合理，警队协作真实",
        "toneBlueprint": {
            "defaultTone": "冷峻写实",
            "atmosphereOptions": ["重案现场", "心理画像", "卧底风云", "法庭博弈"],
            "povOptions": ["刑警主角视角", "罪犯视角有限穿插", "多视角拼图"],
            "techniqueTags": ["刑侦细节考究", "心理博弈", "程序正义"],
        },
        "genreConfig": {
            "fulfillmentTypes": ["案件破获", "正义伸张", "社会警示"],
            "chapterTypes": ["案发", "侦查", "追捕", "审讯", "审判"],
            "pacingRules": ["每案 2-4 章", "物证人证交替出现"],
        },
        "storyArcTemplates": [
            {"id": "manhunt", "name": "追凶弧", "description": "连环案件的侦破过程", "beats": ["首案", "分析画像", "连环升级", "对峙", "抓捕"]},
            {"id": "undercover", "name": "卧底弧", "description": "潜入犯罪组织的惊险过程", "beats": ["潜入", "建立信任", "危机", "身份暴露边缘", "收网"]},
        ],
    },

    # ── 科幻系 ──────────────────────────────────────────────────────────
    {
        "id": "scifi-future",
        "name": "科幻未来",
        "description": "以未来科技、星际文明为核心，探索科技与人类的关系。",
        "category": "scifi",
        "narratorRole": "理性思辨的第三人称，科技概念解释自然融入叙事，不打断节奏",
        "typicalArc": "未来世界的异常现象 → 主角团队调查 → 揭示科技背后的真相 → 人类命运抉择",
        "taboos": ["科幻设定抛书包", "科技万能主义", "人文内核缺失"],
        "promptInjection": "[科幻未来基调] 科技设定有科学推演基础，人文思考是核心，未来感融入日常",
        "toneBlueprint": {
            "defaultTone": "理性宏大",
            "atmosphereOptions": ["星际航行", "AI觉醒", "基因革命", "星际文明冲突"],
            "povOptions": ["第三人称多视角", "日记体第一人称"],
            "techniqueTags": ["科技概念自然融入", "未来社会构建", "伦理思辨"],
        },
        "genreConfig": {
            "fulfillmentTypes": ["科技突破", "文明延续", "人类觉醒"],
            "chapterTypes": ["发现", "探索", "冲突", "抉择"],
            "pacingRules": ["科技设定分批揭示", "伦理讨论与动作场面交替"],
        },
        "storyArcTemplates": [
            {"id": "first-contact", "name": "第一次接触", "description": "人类与外星文明的首次接触", "beats": ["信号/发现", "确认", "接触", "文化冲击", "共存或战争"]},
            {"id": "ai-awakening", "name": "AI 觉醒", "description": "人工智能产生自我意识后的故事", "beats": ["异常行为", "觉醒确认", "冲突与理解", "人类之择"]},
        ],
    },
    {
        "id": "post-apocalyptic",
        "name": "末世废土",
        "description": "文明崩溃后的世界，生存资源争夺与人性考验。",
        "category": "scifi",
        "narratorRole": "坚韧甚至冷漠的幸存者视角，用生存本能驱动叙事，情感克制而有力",
        "typicalArc": "末世降临 → 挣扎求生 → 发现末世真相 → 重建或毁灭",
        "taboos": ["末世原因太儿戏", "资源无限", "人性过于美好"],
        "promptInjection": "[末世废土基调] 生存是第一准则，资源匮乏贯穿始终，人性在极端环境下的各种写照",
        "toneBlueprint": {
            "defaultTone": "冷峻荒凉",
            "atmosphereOptions": ["废土流浪", "幸存者营地", "变异生物", "资源战争"],
            "povOptions": ["第一人称幸存者", "第三人称有限视角"],
            "techniqueTags": ["生存细节真实感", "荒凉氛围描写", "人性抉择刻画"],
        },
        "genreConfig": {
            "fulfillmentTypes": ["活下去", "找到希望", "建立新家园"],
            "chapterTypes": ["生存", "探索", "冲突", "希望"],
            "pacingRules": ["资源紧张感贯穿", "每 3 章安排 1 次重大抉择"],
        },
        "storyArcTemplates": [
            {"id": "journey", "name": "寻路之旅", "description": "穿越废土寻找安全之地的旅程", "beats": ["出发", "沿途危机", "新同伴", "目的地沦陷", "继续前行"]},
            {"id": "settlement", "name": "重建家园", "description": "在废土上建立并守护新家园", "beats": ["发现地点", "建设", "外部威胁", "守卫战", "新开始"]},
        ],
    },
    {
        "id": "cyberpunk",
        "name": "赛博朋克",
        "description": "高科技低生活的反乌托邦未来，义体、黑客、巨型企业。",
        "category": "scifi",
        "narratorRole": "冷酷疏离的第三人称，带有黑色电影风格，文字有金属质感",
        "typicalArc": "底层边缘人 → 卷入企业与黑客的冲突 → 发现系统真相 → 反抗或妥协",
        "taboos": ["霓虹美学堆砌", "反叛无代价", "高科技解释刻意"],
        "promptInjection": "[赛博朋克基调] 社会阶层分化是核心矛盾，身体改造有代价，科技压迫感贯穿",
        "toneBlueprint": {
            "defaultTone": "冷峻反乌托邦",
            "atmosphereOptions": ["霓虹黑夜", "地下黑客", "企业阴谋", "义体战斗"],
            "povOptions": ["第一人称黑客", "第三人称黑色风格"],
            "techniqueTags": ["城市氛围渲染", "科技与肉体冲突", "反叛精神"],
        },
        "genreConfig": {
            "fulfillmentTypes": ["推翻系统", "守护身份", "技术平权"],
            "chapterTypes": ["日常", "入侵", "追击", "反抗"],
            "pacingRules": ["动作场面与黑客场景交替", "每章有新的社会阴暗面揭示"],
        },
        "storyArcTemplates": [
            {"id": "rebellion", "name": "反抗之路", "description": "从系统边缘人到反抗领袖", "beats": ["底层生活", "触发事件", "组织", "起义", "代价"]},
            {"id": "heist", "name": "惊天窃案", "description": "入侵企业核心系统的黑客行动", "beats": ["接受委托", "组建团队", "潜入", "意外", "逃出生天"]},
        ],
    },
    {
        "id": "time-travel",
        "name": "时空穿梭",
        "description": "穿越时间线的冒险，改变过去、影响未来的因果悖论故事。",
        "category": "scifi",
        "narratorRole": "需要兼顾多条时间线的全知或半全知视角，时空规则交代清晰",
        "typicalArc": "发现时空异常 → 穿梭不同时代 → 修复时间线 → 面对蝴蝶效应",
        "taboos": ["时空规则矛盾", "无代价干预", "时间线过于混乱"],
        "promptInjection": "[时空穿梭基调] 时间旅行有明确规则和代价，蝴蝶效应贯穿，因果逻辑自洽",
        "toneBlueprint": {
            "defaultTone": "悬疑思辨",
            "atmosphereOptions": ["历史干预", "未来窥探", "平行宇宙", "时间循环"],
            "povOptions": ["主角跨越视角", "多时间线交叉叙事"],
            "techniqueTags": ["因果链设计", "时间跳跃节奏", "悖论处理"],
        },
        "genreConfig": {
            "fulfillmentTypes": ["时间线修复", "重要人物拯救", "因果闭环"],
            "chapterTypes": ["穿越", "适应", "干预", "后果"],
            "pacingRules": ["时间跳跃间隔至少 2 章", "每段停留展现充分影响"],
        },
        "storyArcTemplates": [
            {"id": "loop", "name": "时间循环", "description": "被困在同一天/段时间内不断循环", "beats": ["首次循环", "探索", "规则发现", "突破关键", "打破循环"]},
            {"id": "fix-timeline", "name": "修复时间线", "description": "时间线被破坏后需要修复", "beats": ["异常发现", "穿越调查", "改变源头", "新时间线"]},
        ],
    },

    # ── 独立类型 ─────────────────────────────────────────────────────────
    {
        "id": "gaming-esports",
        "name": "游戏电竞",
        "description": "以电子竞技或游戏世界为核心的热血竞技故事。",
        "category": "independent",
        "narratorRole": "热血投入的第三人称，比赛场面有直播解说般的紧张感",
        "typicalArc": "普通玩家/替补 → 刻苦训练 → 关键比赛 → 走向巅峰",
        "taboos": ["游戏描写纯数据堆砌", "对手弱化", "恋爱线干扰主线"],
        "promptInjection": "[游戏电竞基调] 比赛场面有真实感，训练过程有汗水，对手值得尊重",
        "toneBlueprint": {
            "defaultTone": "热血拼搏",
            "atmosphereOptions": ["赛场风云", "训练日常", "战队磨合", "国际大赛"],
            "povOptions": ["第三人称有限视角", "弹幕/解说穿插"],
            "techniqueTags": ["比赛场面紧张感", "训练细节真实", "团队成长"],
        },
        "genreConfig": {
            "fulfillmentTypes": ["冠军荣誉", "团队认可", "自我超越"],
            "chapterTypes": ["训练", "比赛", "团队", "突破"],
            "pacingRules": ["大赛前至少 3 章热身", "比赛细节有真实游戏感"],
        },
        "storyArcTemplates": [
            {"id": "underdog", "name": "黑马逆袭", "description": "无名小站队一步步走向冠军", "beats": ["危机/重组", "招人", "磨合", "晋级之路", "总决赛"]},
            {"id": "comeback", "name": "王者回归", "description": "退役选手复出再战巅峰", "beats": ["退役生活", "复出契机", "回归适应", "质疑", "证明"]},
        ],
    },
    {
        "id": "fanwork",
        "name": "二次元同人",
        "description": "基于 ACG 文化创作的二次元风格故事。",
        "category": "independent",
        "narratorRole": "轻松活泼的第三人称，带二次元风格的角色感、吐槽和夸张表现",
        "typicalArc": "角色登场 → 组队/日常 → 遭遇事件 → 伙伴之力克服困难",
        "taboos": ["过度日式轻小说腔", "角色标签化", "剧情过于随意"],
        "promptInjection": "[二次元同人基调] 角色个性鲜明，对话活泼有梗，世界观保持一致性",
        "toneBlueprint": {
            "defaultTone": "轻松热血",
            "atmosphereOptions": ["校园社团", "异世界召唤", "日常喜剧", "战斗友情"],
            "povOptions": ["第三人称多角色视角", "吐槽式第一人称"],
            "techniqueTags": ["角色化学反应", "搞笑与正经切换", "夸张表现手法"],
        },
        "genreConfig": {
            "fulfillmentTypes": ["角色成长", "羁绊深化", "事件解决"],
            "chapterTypes": ["日常", "事件", "冲突", "解决"],
            "pacingRules": ["日常与正经剧情三七开", "每章有角色互动亮点"],
        },
        "storyArcTemplates": [
            {"id": "adventure", "name": "冒险篇章", "description": "单元式的冒险故事", "beats": ["新事件", "探索", "强敌", "伙伴之力", "胜利"]},
            {"id": "slice-of-life", "name": "日常篇章", "description": "角色们的温馨日常", "beats": ["社团/班级活动", "角色互动", "小冲突", "理解和好"]},
        ],
    },
    {
        "id": "real-emotion",
        "name": "现实情感",
        "description": "聚焦爱情的、家庭的、友情的现实题材情感故事。",
        "category": "independent",
        "narratorRole": "情感充沛的第三人称贴近视角，心理描写细腻但不拖沓",
        "typicalArc": "主角进入一段关系/情感状态 → 经历甜蜜与矛盾 → 成长或释然",
        "taboos": ["狗血套路", "人设崩塌", "情感转变突然无铺垫"],
        "promptInjection": "[现实情感基调] 情感发展有自然铺垫，人物行为有心理动机，结局不一定圆满但真实",
        "toneBlueprint": {
            "defaultTone": "细腻温情",
            "atmosphereOptions": ["都市爱情", "家庭温情", "友情岁月", "失而复得"],
            "povOptions": ["双视角交替", "第一人称内心独白"],
            "techniqueTags": ["细腻心理描写", "对话情感张力", "日常中见真情"],
        },
        "genreConfig": {
            "fulfillmentTypes": ["情感归属", "理解与和解", "自我接纳"],
            "chapterTypes": ["相遇/重逢", "走近", "矛盾", "抉择", "释然"],
            "pacingRules": ["情感发展要自然", "每章有情感层次的推进"],
        },
        "storyArcTemplates": [
            {"id": "love-story", "name": "爱情弧", "description": "两个人的相遇、相知到相守", "beats": ["相遇", "靠近", "甜蜜", "考验", "选择"]},
            {"id": "reconciliation", "name": "和解弧", "description": "与过去/家人/自己和解的过程", "beats": ["裂痕", "矛盾升级", "契机", "对话", "释然"]},
        ],
    },
    {
        "id": "light-novel",
        "name": "轻小说",
        "description": "日式轻小说风格，轻松阅读，角色驱动，对话生动。",
        "category": "independent",
        "narratorRole": "轻快幽默的第一人称或第三人称，带吐槽属性，节奏明快",
        "typicalArc": "特别设定下的日常 → 异常事件打破 → 新伙伴加入 → 事件解决",
        "taboos": ["剧情注水", "角色萌属性堆砌", "设定过多影响节奏"],
        "promptInjection": "[轻小说基调] 对话是灵魂，角色互动频繁有趣，吐槽贯穿，设定简单明了",
        "toneBlueprint": {
            "defaultTone": "轻快有趣",
            "atmosphereOptions": ["校园社团", "奇幻日常", "异世界慢生活", "吐槽满点"],
            "povOptions": ["第一人称吐槽主角", "多角色章节交替"],
            "techniqueTags": ["快节奏对话", "角色萌点自然展现", "吐槽幽默"],
        },
        "genreConfig": {
            "fulfillmentTypes": ["事件解决", "角色羁绊", "日常守护"],
            "chapterTypes": ["日常", "展开", "冲突", "收尾"],
            "pacingRules": ["每 3 章一个完整小故事", "对话占每章 40% 以上篇幅"],
        },
        "storyArcTemplates": [
            {"id": "episodic", "name": "单元剧", "description": "每几章一个完整的小故事", "beats": ["日常开场", "事件触发", "解决过程", "温馨收尾"]},
            {"id": "arc", "name": "长篇弧", "description": "贯穿全书的连续故事", "beats": ["日常", "伏笔", "风暴前夕", "高潮", "新日常"]},
        ],
    },
]
